-- 与 M0~M3 期间由 Hibernate ddl-auto=update 生成的结构保持一致

CREATE TABLE IF NOT EXISTS ping_message (
    id   BIGINT NOT NULL,
    text VARCHAR(255),
    PRIMARY KEY (id)
);

CREATE TABLE IF NOT EXISTS card (
    id            BIGINT GENERATED BY DEFAULT AS IDENTITY,
    front         TEXT NOT NULL,
    back          TEXT,
    created_at    TIMESTAMP(6) WITH TIME ZONE NOT NULL,
    due_at        TIMESTAMP(6) WITH TIME ZONE NOT NULL,
    interval_days INTEGER NOT NULL,
    repetitions   INTEGER NOT NULL,
    ease_factor   FLOAT(53) NOT NULL,
    lapses        INTEGER NOT NULL,
    PRIMARY KEY (id)
);

CREATE TABLE IF NOT EXISTS review_log (
    id                  BIGINT GENERATED BY DEFAULT AS IDENTITY,
    card_id             BIGINT NOT NULL,
    reviewed_at         TIMESTAMP(6) WITH TIME ZONE NOT NULL,
    rating              VARCHAR(16) NOT NULL CHECK (rating IN ('AGAIN', 'HARD', 'GOOD')),
    interval_after_days INTEGER NOT NULL,
    PRIMARY KEY (id)
);

CREATE INDEX IF NOT EXISTS idx_review_log_card ON review_log (card_id);
