-- 把学习状态从 card 拆到 user_card_state，并引入 app_user。
-- Flyway 会把整个脚本包在一个事务里（PG 的 DDL 可回滚），中途失败自动回滚。

-- 1. 用户表 -------------------------------------------------------------
CREATE TABLE app_user (
                          id            bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                          username      text        NOT NULL UNIQUE,
                          password_hash text        NOT NULL,
                          created_at    timestamptz NOT NULL DEFAULT now()
);

-- 占位账号：'NOT_SET' 不是合法 bcrypt 串，任何密码都匹配不上，
-- 所以 M4-3 手动 UPDATE 成真哈希之前，这个账号登不进来。
INSERT INTO app_user (username, password_hash) VALUES ('keshi', 'NOT_SET');

-- 2. card 归属 ----------------------------------------------------------
ALTER TABLE card ADD COLUMN owner_id bigint;
UPDATE card SET owner_id = (SELECT id FROM app_user WHERE username = 'keshi');
ALTER TABLE card ALTER COLUMN owner_id SET NOT NULL;
ALTER TABLE card ADD CONSTRAINT fk_card_owner
    FOREIGN KEY (owner_id) REFERENCES app_user (id);

-- 还掉 M2 的技术债：同一用户下 front 唯一（原来靠应用层 check-then-act）
ALTER TABLE card ADD CONSTRAINT uk_card_owner_front UNIQUE (owner_id, front);

-- 3. 学习状态表 ---------------------------------------------------------
CREATE TABLE user_card_state (
                                 id            bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                                 user_id       bigint           NOT NULL REFERENCES app_user (id),
                                 card_id       bigint           NOT NULL REFERENCES card (id) ON DELETE CASCADE,
                                 due_at        timestamptz      NOT NULL,
                                 interval_days integer          NOT NULL,
                                 repetitions   integer          NOT NULL,
                                 ease_factor   double precision NOT NULL,
                                 lapses        integer          NOT NULL,
                                 CONSTRAINT uk_state_user_card UNIQUE (user_id, card_id)
);

-- 4. 搬数据（全脚本唯一会丢东西的一步）-----------------------------------
INSERT INTO user_card_state
(user_id, card_id, due_at, interval_days, repetitions, ease_factor, lapses)
SELECT c.owner_id, c.id, c.due_at, c.interval_days, c.repetitions, c.ease_factor, c.lapses
FROM card c;

-- 「今天该复习什么」的索引
CREATE INDEX idx_state_user_due ON user_card_state (user_id, due_at);

-- 5. 数据搬完了，才删旧列 ------------------------------------------------
ALTER TABLE card
DROP COLUMN due_at,
    DROP COLUMN interval_days,
    DROP COLUMN repetitions,
    DROP COLUMN ease_factor,
    DROP COLUMN lapses;

-- 6. review_log 加用户 --------------------------------------------------
ALTER TABLE review_log ADD COLUMN user_id bigint;
UPDATE review_log SET user_id = (SELECT id FROM app_user WHERE username = 'keshi');
ALTER TABLE review_log ALTER COLUMN user_id SET NOT NULL;
ALTER TABLE review_log ADD CONSTRAINT fk_review_log_user
    FOREIGN KEY (user_id) REFERENCES app_user (id);