-- 卡片分包（牌组）。存量卡片全部归入每个用户的「默认包」。

CREATE TABLE deck (
                      id         bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                      owner_id   bigint      NOT NULL REFERENCES app_user (id),
                      name       text        NOT NULL,
                      created_at timestamptz NOT NULL DEFAULT now(),
                      CONSTRAINT uk_deck_owner_name UNIQUE (owner_id, name)
);

-- 每个用户先有一个默认包，存量卡片才有地方放
INSERT INTO deck (owner_id, name) SELECT id, '默认包' FROM app_user;

ALTER TABLE card ADD COLUMN deck_id bigint;
UPDATE card c SET deck_id = (
    SELECT d.id FROM deck d WHERE d.owner_id = c.owner_id AND d.name = '默认包'
);
ALTER TABLE card ALTER COLUMN deck_id SET NOT NULL;
ALTER TABLE card ADD CONSTRAINT fk_card_deck FOREIGN KEY (deck_id) REFERENCES deck (id);

-- 唯一性从「用户 + 正面」收窄到「包 + 正面」：
-- 同一个词可以在不同包里各存一张，各自独立记进度。
ALTER TABLE card DROP CONSTRAINT uk_card_owner_front;
ALTER TABLE card ADD CONSTRAINT uk_card_deck_front UNIQUE (deck_id, front);

CREATE INDEX idx_card_deck ON card (deck_id);
