-- 读过的文章。正文按 Anki 的方括号记法存注音（諦[あきら]める），
-- 跟卡片用的是同一套记法，前端同一个 Furigana 组件渲染。

CREATE TABLE article (
                         id         bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                         owner_id   bigint      NOT NULL REFERENCES app_user (id),
                         title      text        NOT NULL,
                         body       text        NOT NULL,
                         source_url text,
                         created_at timestamptz NOT NULL DEFAULT now()
);

-- 列表按保存时间倒序，这是唯一的查询方式
CREATE INDEX idx_article_owner_created ON article (owner_id, created_at DESC);
