-- 登录加固：会话落库、邮箱找回、GitHub 登录。

-- 1. Spring Session 的表 -------------------------------------------------
-- 照抄 spring-session-jdbc 自带的 schema-postgresql.sql。不让它自己建表
-- （spring.session.jdbc.initialize-schema=never）：schema 统一归 Flyway 管。
-- 不加引号的大写名在 PG 里会被折成小写，和它运行时发的 SQL 对得上。
CREATE TABLE SPRING_SESSION (
    PRIMARY_ID            CHAR(36) NOT NULL,
    SESSION_ID            CHAR(36) NOT NULL,
    CREATION_TIME         BIGINT   NOT NULL,
    LAST_ACCESS_TIME      BIGINT   NOT NULL,
    MAX_INACTIVE_INTERVAL INT      NOT NULL,
    EXPIRY_TIME           BIGINT   NOT NULL,
    PRINCIPAL_NAME        VARCHAR(100),
    CONSTRAINT SPRING_SESSION_PK PRIMARY KEY (PRIMARY_ID)
);

CREATE UNIQUE INDEX SPRING_SESSION_IX1 ON SPRING_SESSION (SESSION_ID);
CREATE INDEX SPRING_SESSION_IX2 ON SPRING_SESSION (EXPIRY_TIME);
CREATE INDEX SPRING_SESSION_IX3 ON SPRING_SESSION (PRINCIPAL_NAME);

CREATE TABLE SPRING_SESSION_ATTRIBUTES (
    SESSION_PRIMARY_ID CHAR(36)     NOT NULL,
    ATTRIBUTE_NAME     VARCHAR(200) NOT NULL,
    ATTRIBUTE_BYTES    BYTEA        NOT NULL,
    CONSTRAINT SPRING_SESSION_ATTRIBUTES_PK PRIMARY KEY (SESSION_PRIMARY_ID, ATTRIBUTE_NAME),
    CONSTRAINT SPRING_SESSION_ATTRIBUTES_FK FOREIGN KEY (SESSION_PRIMARY_ID)
        REFERENCES SPRING_SESSION (PRIMARY_ID) ON DELETE CASCADE
);

-- 2. 邮箱 -----------------------------------------------------------------
-- 只存验证过的邮箱；验证中的新邮箱放在 auth_token.email 里，点了链接才落到这儿。
-- 一律小写存，唯一约束才有意义。
ALTER TABLE app_user ADD COLUMN email text UNIQUE;

-- 3. 一次性令牌：邮箱验证、密码重置 ----------------------------------------
-- 只存 SHA-256，原文只出现在发出去的邮件里 —— 库泄露了也拿不到能用的链接。
CREATE TABLE auth_token (
    id         bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_id    bigint      NOT NULL REFERENCES app_user (id) ON DELETE CASCADE,
    purpose    text        NOT NULL,
    token_hash text        NOT NULL UNIQUE,
    email      text,
    expires_at timestamptz NOT NULL,
    used_at    timestamptz,
    created_at timestamptz NOT NULL DEFAULT now()
);

CREATE INDEX auth_token_user_purpose ON auth_token (user_id, purpose);

-- 4. 第三方登录身份 ---------------------------------------------------------
-- 认的是 GitHub 的数字 id，不是 login：login 用户可以改，id 不会变。
CREATE TABLE oauth_identity (
    id               bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_id          bigint      NOT NULL REFERENCES app_user (id) ON DELETE CASCADE,
    provider         text        NOT NULL,
    provider_user_id text        NOT NULL,
    provider_login   text,
    created_at       timestamptz NOT NULL DEFAULT now(),
    UNIQUE (provider, provider_user_id),
    UNIQUE (user_id, provider)
);
