-- self：随笔。只有一个人写、谁都能读，所以不挂 owner_id —— 谁能写由配置里的 self.owner 决定。
-- 一天可以写好几条，按天分组是前端的事；这里只记下落笔的时刻。

CREATE TABLE essay (
                       id         bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                       body       text        NOT NULL,
                       written_at timestamptz NOT NULL DEFAULT now(),
                       edited_at  timestamptz
);

-- 列表按 id 倒序翻页：id 和落笔时刻同序，而且不会撞
-- （主键索引就够用，不另建）
