spring.application.name=kotoba
spring.datasource.url=jdbc:postgresql://localhost:5432/kotoba
spring.datasource.username=kotoba
spring.datasource.password=kotoba_dev_pw

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true

spring.sql.init.mode=always
spring.jpa.defer-datasource-initialization=true